### ISSUE TITLE
Python 3.11 support

### ISSUE THREAD

**Issue by mstoelzle** [cgarciae/ciclo#5]
Thanks, Cristian for developing this awesome library! I think it will definitely be very useful for the JAX community.

I noticed the following issue:

When I tried to install via `pip install ciclo`, I get an error that it _Could not find a version that satisfies the requirement ciclo_. I think the reason is that I have Python 3.11 installed and you are excluding it here: https://github.com/cgarciae/ciclo/blob/main/pyproject.toml#L9

Now, I would like to ask is there a specific reason you are excluding 3.11? If not, I would like to kindly ask you to relax this requirement.

**Comment by cgarciae** [comment]
Hey! Thanks for reporting this!
Let me try to relax the requirements :)

**Comment by cgarciae** [comment]
Fixed in `0.1.8`
